import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Valorant Agents",
    description: "Generated by create next app",
    icons: {
        icon: ['/favicon.png'], // Path to your favicon
        apple: ['/apple-touch-icon.png'], // Optional: path to your apple touch icon
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
